### ISSUE TITLE
Cannot save any SQS Queue

### ISSUE THREAD

**Issue by daniele-xp** [jenkinsci/aws-codecommit-trigger-plugin#37]
Versions:
* Jenkins ver. 2.60.3 (tried also 2.76)
* AWS CodeCommit Trigger Plugin ver. 2.0.1 (latest)

Steps to reproduce:
* Jenkins > Manage Jenkins > Configure System > AWS Code Commit Trigger SQS Plugin
* Select the right AWS Credential (created before)
* Select the right AWS Region
* Select any SQS Queue available from the dropdown
* Test access: everything is ok (:arrow_right: Access to SQS successful)
* Click on Save (or on Apply)
* Return to Jenkins > Manage Jenkins > Configure System > AWS Code Commit Trigger SQS Plugin
* Nothing is saved and the SQS Queue is not available on Job configuration panel

Tried also with a clean new Jenkins installation.

**Comment by ronaldtse** [comment]
@daniele-xp apologies on this. @phuonghuynh could you have take a look? Thanks!

**Comment by phuonghuynh** [comment]
thanks @daniele-xp

**Comment by phuonghuynh** [comment]
Fixed in v2.0.2 released

**Comment by ronaldtse** [comment]
Thanks @phuonghuynh and @daniele-xp !

**Comment by ronaldtse** [comment]
@daniele-xp let us know if this can be closed. Thanks!

**Comment by daniele-xp** [comment]
This issue seems resolved, but I tried today the new version and the integration with AWS seems broken now.

I tried to reconfigure the SQS queue. Saved and tested the SQS connection. When there are available messages into my aws queue, they are not read by jenkins and nothing appears in the SQS Activity log.

Everything was working with the v1.15.

**Comment by phuonghuynh** [comment]
apologies on this, could i have some Jenkins log to investigate this issue ?

**Comment by daniele-xp** [comment]
@phuonghuynh 

```
Monitor for https://sqs.us-east-1.amazonaws.com/xxxxxxxxx/xxxxxxx-queue stopped, error: com.amazonaws.services.sqs.model.AmazonSQSException: Access to the resource https://sqs.us-east-1.amazonaws.com/xxxxxxxxx/xxxxxxxxxxxx-queue is denied. (Service: AmazonSQS; Status Code: 403; Error Code: AccessDenied; Request ID: xxxxxxxxxxx)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1587)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1257)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1740)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1716)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeGetQueueAttributes(AmazonSQSClient.java:1013)
	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueAttributes(AmazonSQSClient.java:989)
	at com.amazonaws.services.sqs.buffered.ReceiveQueueBuffer.spawnMoreReceiveTasks(ReceiveQueueBuffer.java:312)
	at com.amazonaws.services.sqs.buffered.ReceiveQueueBuffer.receiveMessageAsync(ReceiveQueueBuffer.java:150)
	at com.amazonaws.services.sqs.buffered.QueueBuffer.receiveMessage(QueueBuffer.java:171)
	at com.amazonaws.services.sqs.buffered.QueueBuffer.receiveMessageSync(QueueBuffer.java:188)
	at com.amazonaws.services.sqs.buffered.AmazonSQSBufferedAsyncClient.receiveMessage(AmazonSQSBufferedAsyncClient.java:155)
	at com.ribose.jenkins.plugin.awscodecommittrigger.net.SQSChannelImpl.getMessages(SQSChannelImpl.java:60)
	at com.ribose.jenkins.plugin.awscodecommittrigger.threading.SQSQueueMonitorImpl.processMessages(SQSQueueMonitorImpl.java:154)
	at com.ribose.jenkins.plugin.awscodecommittrigger.threading.SQSQueueMonitorImpl.run(SQSQueueMonitorImpl.java:110)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Seems an authentication problem with AWS.
Nonetheless, the test connection into Jenkins Settings works properly.

**Comment by phuonghuynh** [comment]
Thanks for the log, @daniele-xp 

Any additional information which you think is relevant to this issue? Could i have your config pics (Job Trigger Config & Git Config)? The sensitive information can be hidden.

Yes, its working for me. 
<img width="1626" alt="screenshot at oct 03 17-16-19" src="https://user-images.githubusercontent.com/705510/31120537-017dd402-a85f-11e7-9cf9-f34b5bd3a0d8.png">

<img width="1305" alt="screenshot at oct 03 17-17-58" src="https://user-images.githubusercontent.com/705510/31120536-017a903a-a85f-11e7-9f5b-35bd0bf1d8b5.png">

**Comment by daniele-xp** [comment]
![screen shot 2017-10-03 at 12 52 56](https://user-images.githubusercontent.com/14909433/31121958-768a2540-a83a-11e7-8619-35903590b417.png)
![screen shot 2017-10-03 at 12 52 06](https://user-images.githubusercontent.com/14909433/31121966-7b2a0b42-a83a-11e7-9c20-2e14d306766a.png)
![screen shot 2017-10-03 at 13 00 48](https://user-images.githubusercontent.com/14909433/31122140-0289d1e4-a83b-11e7-88f5-8c5fc3704d8a.png)
![screen shot 2017-10-03 at 12 59 03](https://user-images.githubusercontent.com/14909433/31122060-c575aba2-a83a-11e7-9408-c15d63048761.png)

Seems a problem related to the authentication during the queue polling in AmazonSQSClient. In some way it is different from the authentication used into the settings page for the "Test Access" button.

**Comment by phuonghuynh** [comment]
Could you check the credential has access right to GET messages as well as DELETE messages as required by the plugin?

You right, the validation in the test connection not check permissions required by the plugin, new issue added for it can here https://github.com/riboseinc/aws-codecommit-trigger-plugin/issues/44

**Comment by daniele-xp** [comment]
@phuonghuynh the credential has full access to the queue and it the same credential that is working with the v1.15

**Comment by phuonghuynh** [comment]
:honeybee: interesting issue

**Comment by phuonghuynh** [comment]
@ronaldtse any idea on this?

**Comment by phuonghuynh** [comment]
@daniele-xp you getting this issue with fresh install of last version of the plugin, v2.0.2 ?

**Comment by ronaldtse** [comment]
@daniele-xp would you mind letting us know the exact permissions that your account has on the SQS queue has? It's probably not the IAM Managed Policy `AmazonSQSFullAccess`.

Specifically, does the account have these permissions on the SQS queue?
```
ChangeMessageVisibility
ChangeMessageVisibilityBatch
DeleteMessage
DeleteMessageBatch
GetQueueAttributes
GetQueueUrl
ReceiveMessage
SetQueueAttributes
```

**Comment by daniele-xp** [comment]
@ronaldtse @phuonghuynh it has AmazonSQSFullAccess

![screen shot 2017-10-10 at 12 20 43](https://user-images.githubusercontent.com/14909433/31381806-e50c6b6a-adb5-11e7-93ed-447ca84df6e8.png)
![screen shot 2017-10-10 at 12 21 31](https://user-images.githubusercontent.com/14909433/31381811-e7963f96-adb5-11e7-9e65-7132a1453a81.png)

and I want to reiterate: it is the same credential that was working with the v1.15

**Comment by ronaldtse** [comment]
Understand @daniele-xp . That's very strange...

**Comment by phuonghuynh** [comment]
@daniele-xp is this issue also happening for fresh install of last version v2.0.2 ?

**Comment by phuonghuynh** [comment]
@daniele-xp could you also check with SQS Queue permission panel, since AWS Permission explicit `deny` always overrides an `allow`, see http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-using-identity-based-policies.html

I also want to narrowed it down to just two possibilities
  - Upgrade from v1.x to v2.x or 
  - Fresh install of v2.x

or both, might be :/

**Comment by daniele-xp** [comment]
It seems ok to me

![screen shot 2017-10-10 at 17 04 23](https://user-images.githubusercontent.com/14909433/31393987-6c693cec-addd-11e7-926d-f66f05534d72.png)

**Comment by daniele-xp** [comment]
I just tried with a clean Jenkins local installation and the problem seems identically:

```
Monitor for https://sqs.us-east-1.amazonaws.com/xxxxxxxxxxxx/gateway-commit-queue stopped, error: com.amazonaws.services.sqs.model.AmazonSQSException: Access to the resource https://sqs.us-east-1.amazonaws.com/xxxxxxxxxx/gateway-commit-queue is denied. (Service: AmazonSQS; Status Code: 403; Error Code: AccessDenied; Request ID: 473ffafe-5d09-5c61-9994-a8a8ba6a35ba)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1587)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1257)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1029)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:741)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:715)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:697)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:665)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:647)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:511)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1740)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1716)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeGetQueueAttributes(AmazonSQSClient.java:1013)
	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueAttributes(AmazonSQSClient.java:989)
	at com.amazonaws.services.sqs.buffered.ReceiveQueueBuffer.spawnMoreReceiveTasks(ReceiveQueueBuffer.java:312)
	at com.amazonaws.services.sqs.buffered.ReceiveQueueBuffer.receiveMessageAsync(ReceiveQueueBuffer.java:150)
	at com.amazonaws.services.sqs.buffered.QueueBuffer.receiveMessage(QueueBuffer.java:171)
	at com.amazonaws.services.sqs.buffered.QueueBuffer.receiveMessageSync(QueueBuffer.java:188)
	at com.amazonaws.services.sqs.buffered.AmazonSQSBufferedAsyncClient.receiveMessage(AmazonSQSBufferedAsyncClient.java:155)
	at com.ribose.jenkins.plugin.awscodecommittrigger.net.SQSChannelImpl.getMessages(SQSChannelImpl.java:60)
	at com.ribose.jenkins.plugin.awscodecommittrigger.threading.SQSQueueMonitorImpl.processMessages(SQSQueueMonitorImpl.java:154)
	at com.ribose.jenkins.plugin.awscodecommittrigger.threading.SQSQueueMonitorImpl.run(SQSQueueMonitorImpl.java:110)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ronaldtse** [comment]
@daniele-xp it looks like it died here (sorry for not looking carefully at the last trace!):
```
com.amazonaws.services.sqs.AmazonSQSClient.executeGetQueueAttributes(AmazonSQSClient.java:1013)
```

According to this page, http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-using-identity-based-policies.html

There is a permission called `sqs:GetQueueAttributes`. Could you try adding that to the account for accessing this SQS queue?

**Comment by daniele-xp** [comment]
@ronaldtse it has the full access!! `GetQueueAttributes` is already included!

![screen shot 2017-10-10 at 17 31 59](https://user-images.githubusercontent.com/14909433/31395407-f9e35730-ade0-11e7-904a-760635083c4f.png)

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "sqs:*"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```

**Comment by ronaldtse** [comment]
@daniele-xp I have no idea what the issue is 😭 

I noticed in your job config you're using "Manual Subscription". Could you try using "Auto"?

**Comment by phuonghuynh** [comment]
@ronaldtse i am on it

**Comment by daniele-xp** [comment]
@phuonghuynh @ronaldtse no, thank you guys for the nice support 🙂

**Comment by phuonghuynh** [comment]
@daniele-xp v2.0.3 released, hope this fixed your issue

**Comment by daniele-xp** [comment]
Gotcha! Now it seems to work properly!
Congratulations guys! 🎉  👏

**Comment by ronaldtse** [comment]
Thank you @phuonghuynh ! Thank you @daniele-xp !

**Comment by daniele-xp** [comment]
Ouch, unfortunately we already have some other problems now.... 

After a first successful run, now all the general settings have been lost and nothing is working anymore 😭 

![screen shot 2017-10-11 at 11 03 18](https://user-images.githubusercontent.com/14909433/31431571-697488c4-ae74-11e7-9544-6e7605d18ae0.png)

![screen shot 2017-10-11 at 11 04 03](https://user-images.githubusercontent.com/14909433/31431636-8bdb8b88-ae74-11e7-8e0c-828f60ac4b05.png)


```
falling back to default instantiation com.ribose.jenkins.plugin.awscodecommittrigger.SQSScmConfig {"type":"ER","url":"https://git-codecommit.us-east-1.amazonaws.com/v1/repos/WSJiffyP2BGateway","subscribedBranches":"master"}
net.sf.json.JSONException: JSONObject["type"] is not a JSONObject.
	at net.sf.json.JSONObject.getJSONObject(JSONObject.java:2006)
	at com.ribose.jenkins.plugin.awscodecommittrigger.SQSScmConfig$DescriptorImpl.newInstance(SQSScmConfig.java:89)
	at com.ribose.jenkins.plugin.awscodecommittrigger.SQSScmConfig$DescriptorImpl.newInstance(SQSScmConfig.java:84)
	at hudson.model.Descriptor$NewInstanceBindInterceptor.onConvert(Descriptor.java:669)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:621)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:716)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:478)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:777)
	at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:83)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:678)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:478)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:474)
	at hudson.model.Descriptor.newInstance(Descriptor.java:592)
	at com.ribose.jenkins.plugin.awscodecommittrigger.SQSTrigger$DescriptorImpl.newInstance(SQSTrigger.java:278)
	at com.ribose.jenkins.plugin.awscodecommittrigger.SQSTrigger$DescriptorImpl.newInstance(SQSTrigger.java:258)
	at hudson.util.DescribableList.rebuild(DescribableList.java:177)
	at org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty.reconfigure(PipelineTriggersJobProperty.java:150)
	at org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty.reconfigure(PipelineTriggersJobProperty.java:55)
	at hudson.util.DescribableList.rebuild(DescribableList.java:175)
	at hudson.model.Job.doConfigSubmit(Job.java:1305)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.interceptor.RequirePOST$Processor.invoke(RequirePOST.java:52)
	at org.kohsuke.stapler.PreInvokeInterceptedFunction.invoke(PreInvokeInterceptedFunction.java:26)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:248)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.MetaClass$5.doDispatch(MetaClass.java:248)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)
	at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:138)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:92)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:564)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
	at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Oct 11, 2017 11:04:40 AM WARNING [c.r.j.p.a.t.SQSQueueMonitorImpl][thread-000094] 
Monitor for https://sqs.us-east-1.amazonaws.com/251031328468/gateway-commit-queue stopped, error: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:131)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1163)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:762)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:724)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1740)
	at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1716)
	at com.amazonaws.services.sqs.AmazonSQSClient.executeGetQueueAttributes(AmazonSQSClient.java:1013)
	at com.amazonaws.services.sqs.AmazonSQSClient.getQueueAttributes(AmazonSQSClient.java:989)
	at com.amazonaws.services.sqs.buffered.ReceiveQueueBuffer.spawnMoreReceiveTasks(ReceiveQueueBuffer.java:312)
	at com.amazonaws.services.sqs.buffered.ReceiveQueueBuffer.receiveMessageAsync(ReceiveQueueBuffer.java:150)
	at com.amazonaws.services.sqs.buffered.QueueBuffer.receiveMessage(QueueBuffer.java:171)
	at com.amazonaws.services.sqs.buffered.QueueBuffer.receiveMessageSync(QueueBuffer.java:188)
	at com.amazonaws.services.sqs.buffered.AmazonSQSBufferedAsyncClient.receiveMessage(AmazonSQSBufferedAsyncClient.java:155)
	at com.ribose.jenkins.plugin.awscodecommittrigger.net.SQSChannelImpl.getMessages(SQSChannelImpl.java:60)
	at com.ribose.jenkins.plugin.awscodecommittrigger.threading.SQSQueueMonitorImpl.processMessages(SQSQueueMonitorImpl.java:154)
	at com.ribose.jenkins.plugin.awscodecommittrigger.threading.SQSQueueMonitorImpl.run(SQSQueueMonitorImpl.java:110)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by phuonghuynh** [comment]
i m checking it

**Comment by daniele-xp** [comment]
Wait a minute @phuonghuynh : this time it might be a my problem

**Comment by daniele-xp** [comment]
@phuonghuynh we can keep it close, sorry 🙏  😅

**Comment by phuonghuynh** [comment]
:sweat:

**Comment by phuonghuynh** [comment]
@daniele-xp we have "display name" field in "Standard Credential" dialog, to use to displayed in "name" column
